# Generated by Django 2.2.7 on 2019-12-29 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksrent',
            name='book_renter',
            field=models.OneToOneField(blank=True, help_text='Пользователь может взять одну книгу', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Арендатор'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
